// data.js
export const jobApplications = [
  {
    id: 1,
    company: 'Infosys',
    title: 'Software Engineer',
    location: 'Bangalore, KA',
    applicationDate: '2024-07-15',
    status: 'Applied',
    interviewDate: '2024-08-10',
    offerDate: '',
    notes: 'Awaiting interview schedule',
  },
  {
    id: 2,
    company: 'Tata Consultancy Services',
    title: 'Data Analyst',
    location: 'Mumbai, MH',
    applicationDate: '2024-08-01',
    status: 'Interview Scheduled',
    interviewDate: '2024-08-20',
    offerDate: '',
    notes: 'Prepare for technical round',
  },
  {
    id: 3,
    company: 'Wipro',
    title: 'Frontend Developer',
    location: 'Delhi, DL',
    applicationDate: '2024-08-05',
    status: 'Offer Received',
    interviewDate: '2024-08-15',
    offerDate: '2024-08-25',
    notes: 'Negotiation in progress',
  },
  {
    id: 4,
    company: 'HCL Technologies',
    title: 'Backend Developer',
    location: 'Chennai, TN',
    applicationDate: '2024-08-10',
    status: 'Rejected',
    interviewDate: '2024-08-18',
    offerDate: '',
    notes: 'Rejected after technical interview',
  },
  {
    id: 5,
    company: 'Tech Mahindra',
    title: 'UX Designer',
    location: 'Hyderabad, TS',
    applicationDate: '2024-08-12',
    status: 'Applied',
    interviewDate: '',
    offerDate: '',
    notes: 'Follow-up required',
  },
  {
    id: 6,
    company: 'Capgemini',
    title: 'Project Manager',
    location: 'Pune, MH',
    applicationDate: '2024-08-15',
    status: 'Interview Scheduled',
    interviewDate: '2024-08-25',
    offerDate: '',
    notes: 'Prepare for managerial round',
  },
  {
    id: 7,
    company: 'L&T Infotech',
    title: 'QA Engineer',
    location: 'Noida, UP',
    applicationDate: '2024-08-18',
    status: 'Applied',
    interviewDate: '',
    offerDate: '',
    notes: 'Awaiting response',
  },
  {
    id: 8,
    company: 'Oracle',
    title: 'Database Administrator',
    location: 'Gurgaon, HR',
    applicationDate: '2024-08-20',
    status: 'Offer Received',
    interviewDate: '2024-08-28',
    offerDate: '2024-09-05',
    notes: 'Review offer details',
  },
  {
    id: 1,
    company: 'Infosys',
    title: 'Software Engineer',
    location: 'Bangalore, KA',
    applicationDate: '2024-07-15',
    status: 'Applied',
    interviewDate: '2024-08-10',
    offerDate: '',
    notes: 'Awaiting interview schedule',
  },
  {
    id: 2,
    company: 'Tata Consultancy Services',
    title: 'Data Analyst',
    location: 'Mumbai, MH',
    applicationDate: '2024-08-01',
    status: 'Interview Scheduled',
    interviewDate: '2024-08-20',
    offerDate: '',
    notes: 'Prepare for technical round',
  },
  {
    id: 3,
    company: 'Wipro',
    title: 'Frontend Developer',
    location: 'Delhi, DL',
    applicationDate: '2024-08-05',
    status: 'Offer Received',
    interviewDate: '2024-08-15',
    offerDate: '2024-08-25',
    notes: 'Negotiation in progress',
  },
  {
    id: 4,
    company: 'HCL Technologies',
    title: 'Backend Developer',
    location: 'Chennai, TN',
    applicationDate: '2024-08-10',
    status: 'Rejected',
    interviewDate: '2024-08-18',
    offerDate: '',
    notes: 'Rejected after technical interview',
  },
  {
    id: 5,
    company: 'Tech Mahindra',
    title: 'UX Designer',
    location: 'Hyderabad, TS',
    applicationDate: '2024-08-12',
    status: 'Applied',
    interviewDate: '',
    offerDate: '',
    notes: 'Follow-up required',
  },
  {
    id: 6,
    company: 'Capgemini',
    title: 'Project Manager',
    location: 'Pune, MH',
    applicationDate: '2024-08-15',
    status: 'Interview Scheduled',
    interviewDate: '2024-08-25',
    offerDate: '',
    notes: 'Prepare for managerial round',
  },
  {
    id: 7,
    company: 'L&T Infotech',
    title: 'QA Engineer',
    location: 'Noida, UP',
    applicationDate: '2024-08-18',
    status: 'Applied',
    interviewDate: '',
    offerDate: '',
    notes: 'Awaiting response',
  },
]
